### ISSUE TITLE
Difference between rollup-plugin-terser and rollup-plugin-uglify

### ISSUE THREAD

**Issue by denniscual** [TrySound/rollup-plugin-terser#1]
Thanks for the contributions! @TrySound . I am just confused about the difference between these 2 plugins? Can you explain me the differences. Thanks.

**Comment by TrySound** [comment]
rollup-plugin-uglify uses uglify-js which is able to transpile only es5 syntax.
rollup-plugin-terser uses terser (the fork of uglify-es) which is able to transpile es6+ syntax.
