### ISSUE TITLE
Bump terser version to avoid terser bug?

### ISSUE THREAD

**Issue by jeberly** [TrySound/rollup-plugin-terser#104]
Hi, 

We just hit this bug using `rollup-plugin-terser`. https://github.com/terser/terser/issues/816

`rollup-plugin-terser` just requires terser version >= `"terser": "^5.0.0"`

Can you require a more recent terser version?  We were able to get around this issue for now, by add `terser` requirement directly to our package.json. 

Thanks!

**Comment by TrySound** [comment]
`^` means freshly installed packages will get the latest terser version. You can uninstall and install rollup-plugin-terser again. Btw adding terser to your package.json cannot solve the problem but maybe you upgraded transitive dependency the same time.
