### ISSUE TITLE
TypeError: terser__default.default is not a function

### ISSUE THREAD

**Issue by barsdeveloper** [TrySound/rollup-plugin-terser#109]
I'm trying to use terser with rollup, followed various tutorial and always encountered this error. I have no other plugins called, just this one. I'm rather new to npm and all that JavaScript stuff so please have patience.

```JavaScript
import terser from 'rollup-plugin-terser'

export default {
    input: 'js/export.js',
    output: {
        file: 'dist/mylibrary.js',
        format: 'es',
        plugins: [
            terser()
        ]
    }
}
```

**Comment by TrySound** [comment]
You could just read this project docs. Import is wrong.
https://github.com/TrySound/rollup-plugin-terser#usage

**Comment by barsdeveloper** [comment]
Thanks, I didn't get that detail
