### ISSUE TITLE
[!] (terser plugin) Error: Farm is ended, no more calls can be done to it

### ISSUE THREAD

**Issue by jdalrymple** [TrySound/rollup-plugin-terser#11]
I keep receiving the above error when running rollup -c. It looks like the error derives from jest:

```
[!] (terser plugin) Error: Farm is ended, no more calls can be done to it
Error: Farm is ended, no more calls can be done to it
    at exports.default.end (/home/hyde/Projects/Libraries/node-gitlab/node_modules/jest-worker/build/index.js:166:13)
    at Object.generateBundle (/home/hyde/Projects/Libraries/node-gitlab/node_modules/rollup-plugin-terser/index.js:38:19)
    at /home/hyde/Projects/Libraries/node-gitlab/node_modules/rollup/dist/rollup.js:20847:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Here is my config:

```
import ts from 'rollup-plugin-typescript2';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import { terser } from "rollup-plugin-terser";
import typescript from 'typescript';
import pkg from './package.json';

export default [
  {
    input: 'src/index.ts',
    output: [
      { file: pkg.module, format: 'esm' }
    ],
    external: [...Object.keys(pkg.dependencies || {})],
    plugins: [
      json(),
      ts({
        typescript,
      }),
      terser(),
    ],
  },
];
```

packages:
```
  "dependencies": {
    "form-data": "^2.3.3",
    "got": "^9.2.2",
    "humps": "^2.0.1",
    "ky": "^0.4.1",
    "randomstring": "^1.1.5"
  },
```

and tsconfig:

```
{
  "compilerOptions": {
    "declaration": false,
   
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,

    "strictPropertyInitialization": true,
    "strictNullChecks": true,

    "target": "es5",
    "module": "es6",
    "outDir": "dist",
    "pretty": true,
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
```

The problem seems to only occur when attempting to compile an es module. If i make a cjs one it works fine. Any suggestions?

**Comment by casz** [comment]
I wonder why it is trying to rollup jest-worker when jest is clearly a devDep ? :|

**Comment by piuccio** [comment]
Having the same problem, I also have jest as dev dep, I'm also using flow

```js
import flow from 'rollup-plugin-flow';
import flowEntry from 'rollup-plugin-flow-entry';
import filesize from 'rollup-plugin-filesize';
import { terser } from 'rollup-plugin-terser';
import pkg from './package.json';

export default {
  input: 'index.js',
  plugins: [
    flow(),
    flowEntry(),
    filesize(),
    terser({ sourcemap: true }),
  ],
  external: Object.keys(pkg.peerDependencies),
```

**Comment by TrySound** [comment]
Jest work is a direct dependency of this project.

What is rollup version you are using?

**Comment by casz** [comment]
@TrySound ^0.66.6 answer is available in https://github.com/jdalrymple/node-gitlab/pull/215/files

**Comment by biyingshuai** [comment]
same problem 
`plugins: [
    progress({
      clearLine: false,
    }),
    clear({ targets: ["dist"] }),
    typescript({
      clean: true,
      rollupCommonJSResolveHack: true,
    }),
    resolve(),
    commonjs({
      include: 'node_modules/**',
    }),
    sourceMaps(),
    // terser(),
    visualizer({
      filename: './statistics.html',
      title: 'schema'
    }),
    sizeSnapshot()
  ],`

**Comment by TrySound** [comment]
I get it. The problem may happen because of multiple outputs. So this is a duplication of [this issue](https://github.com/TrySound/rollup-plugin-terser/issues/5). Use multiple configs instead for now.

**Comment by biyingshuai** [comment]
> I get it. The problem may happen because of multiple outputs. So this is a duplication of [this issue](https://github.com/TrySound/rollup-plugin-terser/issues/5). Use multiple configs instead for now.

Thanks a lot. This solution works for me.

**Comment by jdalrymple** [comment]
Worked for me as well! Ill close this case. Thanks!
