### ISSUE TITLE
Is default exports that bad?

### ISSUE THREAD

**Issue by vincent-thomas** [TrySound/rollup-plugin-terser#113]
> Show me any good language with default exports. It's historical javascriptism.

Well. python?

**Comment by TrySound** [comment]
Example?

**Comment by vincent-thomas** [comment]
For example in python you do this 
```py
from math import example
```
Which is like in js
```js
import { example } from "math"
```
You can also do
```py
import math
math.example
```

**Comment by TrySound** [comment]
Which looks more like namespace import than default

```js
import * as math from 'math';
math.example
```

Default import looks only syntactically similar

**Comment by vincent-thomas** [comment]
> Which looks more like namespace import than default
> 
> ```js
> import * as math from 'math';
> math.example
> ```
> 
> Default import looks only syntactically similar

Whats the difference? Do you mean you cant export something like this in python
```py
from example from math
example()
```

**Comment by TrySound** [comment]
No idea, I don't know python. But fast googling shows there is no default exports in python.

**Comment by vincent-thomas** [comment]
> No idea, I don't know python. But fast googling shows there is no default exports in python.

Maybe not
