### ISSUE TITLE
Option to disable workers?

### ISSUE THREAD

**Issue by mrkishi** [TrySound/rollup-plugin-terser#14]
For some reason, `jest-worker` doesn't seem to work in any of my linux machines right now. I haven't been able to dive deeper to figure out why, but maybe it'd be pertinent to add an option to disable them here?

**Comment by TrySound** [comment]
This is related. You may fix it by specifying numWorkers
https://github.com/TrySound/rollup-plugin-terser/issues/10

**Comment by mrkishi** [comment]
My bad. I was sure I tested it — turns out I tried `{ numworkers: 1 }` instead...
