### ISSUE TITLE
Plugin silently sabotages its work

### ISSUE THREAD

**Issue by while0pass** [TrySound/rollup-plugin-terser#18]
The plugin works fine at my home pc with Ubuntu 18.03, but it silently sabotages its work on our production server with Debian. The problem is that it does start working but creates no target file, and no plugin after it in the pipeline starts doing its job, but rollup returns code 0 as if everything were fine. As I could not figure out the cause of a problem, I tried to switch to other minification plugins. It finds out that rollup-plugin-terser and rollup-plugin-uglify behave the same way (work in one environment and do not work in the other one), but rollup-plugin-babel-minify works pretty well in the both environments. Unfortunately I can't give any more information except that insufficient, but maybe could it suggest some debugging idea to you.

**Comment by TrySound** [comment]
Try to set `numWorkers` option to `1` please

**Comment by while0pass** [comment]
Yes, that solves the issue, thank you very much.

**Comment by adamchipperfield** [comment]
I still get this, despite setting `numWorkers` to `1`...
