### ISSUE TITLE
Error: argname.definition is not a function

### ISSUE THREAD

**Issue by a-xin** [TrySound/rollup-plugin-terser#2]
Hi,

I'm trying to get terser to work on typescript-generated es2015 javascript.

`terser()` plugin is used without any params as the last plugin. The following error is thrown:

```
Error: Error transforming chunk with 'terser' plugin: argname.definition is not a function
    at error (/home/user/app/node_modules/rollup/dist/rollup.js:3356:15)
    at /home/user/app/node_modules/rollup/dist/rollup.js:13582:17
    at <anonymous>
```

rollup: `0.62.0`
rollup-plugin-terser: `1.0.1`

Happy to provide more details (can't share the repo) - is there a debug mode that could provide more details?

**Comment by TrySound** [comment]
Fixed in https://github.com/fabiosantoscode/terser/issues/80
