### ISSUE TITLE
Plugin fails in Node 6 environments

### ISSUE THREAD

**Issue by MartinHelmut** [TrySound/rollup-plugin-terser#23]
## Error

The following error occurs: `SyntaxError: Unexpected token ...`

## Description

Since the changes introduced here: https://github.com/TrySound/rollup-plugin-terser/commit/c096965128d3fa1ebb1b0809a8425fe8a1e5958d#diff-168726dbe96b3ce427e7fedce31bb0bcR12 I cannot run `rollup-plugin-terser` on environments using Node 6. The move from `Object.assign` to the spread operator for objects breaks it.

My suggestions would be to support Node 6 by using `Object.assign` again. I could also provide a PR if wished 🙂

**Comment by TrySound** [comment]
Thank you for the report. I fixed the issue in 4.0.1.
