### ISSUE TITLE
Plugin not working correctly on Jenkins

### ISSUE THREAD

**Issue by semoal** [TrySound/rollup-plugin-terser#25]
Hi TrySound, nice work by the way.

Terser version: 4.0.1
Rollup: 1.0.1

I opened an issue on Rollup this morning about bundling not working on Jenkins but on local (mac and ubuntu 18 working good)
Here it is: https://github.com/rollup/rollup/issues/2632

After a 100% rewrite of my rollup.config.js i've detected removing terser from my output.plugins made it working.

Actual behavior: looks like a process.exit is run or something like this, it exists repently

@TrySound If you want the rollup.config i can share it with you if you need.

**Comment by TrySound** [comment]
Could you try to set numWorkers option to 1?

**Comment by semoal** [comment]
Wow! I'm surprised TrySound, just did the change and worked like a charm.
I'll do some more tests, but looks it's working perfect.

Thanks you mate.

**Comment by TrySound** [comment]
Cool. It's a bug in jest-worker.

**Comment by dekdevy** [comment]
Bumping this, plugin is not working unless numWorkers is set to 1.
Works on local dev machine, but does not even log an error on my vps, it simply shuts down the building process after hanging for a second.
This is on a fresh linux vps with no further modifications.

ubuntu 18.04
nodejs v11.6.0
rollup 1.0.2
rollup-plugin-terser 4.0.1

**Comment by BrandonOCasey** [comment]
We are also seeing this issue on a teamcity ci worker. To get around it we are using the `is-ci` package to detect that we are on a ci and setting the `numWorkers` to 1 when we are on a ci.

**Comment by BrandonOCasey** [comment]
The real problem for us was that the plugin was exiting the process with a successful exit code. This  caused lots of issues

**Comment by semoal** [comment]
Same behaviour on Jenkins, was like a process.exit without displaying any information

**Comment by TrySound** [comment]
Guys, I published patch. Could you try to update plugin and check without numWorkers option?

**Comment by BrandonOCasey** [comment]
This does appear to fix the issue
