### ISSUE TITLE
(feat) option to generate the minified output in a different file

### ISSUE THREAD

**Issue by simonbrunel** [TrySound/rollup-plugin-terser#29]
I think a common use case is to generate both full and minified builds. Currently, this require two rollup configs which, except for the `terser` plugin, are most of the time similar. I'm wondering if it would make sense to introduce a new option to avoid building 2 times?

For example:

```javascript
module.exports = [
    {
        input: input,
        plugins: [
            resolve(),
            commonjs(),
        ],
        output: {
            file: 'foobar.js',
        }
    },
    {
        input: input,
        plugins: [
            resolve(),
            commonjs(),
            terser()
        ],
        output: {
            file: 'foobar.min.js',
        }
    }
]
```

would be:

```javascript
[
    {
        input: input,
        plugins: [
            resolve(),
            commonjs(),
            terser({
                output: {
                    // if not provided, fallback to the same name
                    // as the current entry, and thus replaces it.
                    file: 'foobar.min.js'
                }
            })
        ],
        output: {
            file: 'foobar.js',
        }
    }
]
```

(I'm not suggesting what the API should look like, that's just an example)

**Comment by TrySound** [comment]
It's relevant not in a lot of cases. For example for most react and some other projects we also need to add replace plugin with NODE_ENV.

Your proposal introduces a lot of complexity for both plugin developers and consumers. For developers it requires to take care about writing which is currently done by rollup out of the box. For consumers it increases configuration complexity because output may come from anywhere.

So if the first example works for you it's not worth to make plugin more complex. Bundling libraries is usually fast even with two configs. Apps are usually bundled just once for production.

**Comment by thw0rted** [comment]
I'm new to the plugin and wanted to double check something.  In the front page docs, it gives an example config with multiple output files that differ by `format`:

````js
  output: [
    { file: 'lib.js', format: 'cjs' },
    { file: 'lib.min.js', format: 'cjs' },
    { file: 'lib.esm.js', format: 'es' },
    { dir: '.', entryFileNames: 'lib-[format].js', format: 'iife'  }
  ],
````

Seeing this, I assumed `lib.js` would not be minified but `lib.min.js` would.  If that's supposed to be the case, am I doing something wrong?  This issue makes it sound like that's *not* supposed to be the case -- in that event, why are there two different files that differ only by `format` parameter?

**Comment by TrySound** [comment]
Hi @thw0rted. Sorry, I'm not sure I understand you question.

**Comment by thw0rted** [comment]
OK, I'll try to clarify.  The [example in the docs](https://github.com/TrySound/rollup-plugin-terser#includeexclude) has multiple `output` entries.  I expected that `{ file: 'lib.js', format: 'cjs' }` would create a file that is not minified, and `{ file: 'lib.min.js', format: 'cjs' }` would create a minified file.

I have made a config following the example, and `lib.js` and `lib.min.js` have the exact same contents, both minified by terser.  Was this supposed to happen?  If this is not the correct behavior, I'd like to understand what I'm doing wrong.  If this is the correct behavior, why are both of these lines in the docs?
