### ISSUE TITLE
Error when using `mangle.properties.regex` option

### ISSUE THREAD

**Issue by MaxMilton** [TrySound/rollup-plugin-terser#3]
When passing the `mangle.properties.regex` option the following error is thrown:

```sh
> Building...
    regex.test is not a function

> regex.test is not a function
error Command failed with exit code 1.
```

Example options:

```js
...
terser({
  mangle: {
    properties: {
      regex: /^_.+$/,
    },
  },
});
...
```

Since a regex literal is being used I assume there's a problem serialising it's when it's being passed into the worker (new v2.0.0 feature). I haven't used the `jest-worker` package before so I'm not sure how it passes data exactly. I could imagine a way around this is to convert the regex into a string, send it, and then back into a regex in the worker but I'm not sure that's viable with jest-worker.

**Comment by TrySound** [comment]
Fixed in Fixed in https://github.com/TrySound/rollup-plugin-terser/releases/tag/v3.0.0
