### ISSUE TITLE
Add ts types please to avoid warning

### ISSUE THREAD

**Issue by mecurc** [TrySound/rollup-plugin-terser#30]
Hello, my vscode reported to me that it cannot find types. I know, this is just a warning, but it will be cool if it doesn't exist soon :) 
```
Could not find a declaration file for module 'rollup-plugin-terser'. '/home/dmitry/worker/node_modules/rollup-plugin-terser/index.js' implicitly has an 'any' type.
  Try `npm install @types/rollup-plugin-terser` if it exists or add a new declaration (.d.ts) file containing `declare module 'rollup-plugin-terser';`
```

**Comment by TrySound** [comment]
This is configurable with TS. I don't have to add types to the repo.

**Comment by mecurc** [comment]
No. I have a pure JS project. And any ts configuration without TS binary didn't work for me.

I think adding types for the building project to EVERY project that use this plugin is bad by design.

Visual Studio Code trying to import TS-types for any project. And warns if cannot find it. For reference, please see other popular plugins. They all have typings.

**Comment by TrySound** [comment]
@mecurc I don't see types here.
https://unpkg.com/rollup-plugin-babel@4.3.2/

Adding types to every library which you are looking through vscode is also bad by design.
