### ISSUE TITLE
Add a default export

### ISSUE THREAD

**Issue by green-pickle** [TrySound/rollup-plugin-terser#31]
All rollup plugins except yours are using default exports. Terser plugin import is driving me and my co-workers nuts.

Please add a default export.

**Comment by TrySound** [comment]
I already answered here
https://github.com/TrySound/rollup-plugin-terser/issues/7

**Comment by TrySound** [comment]
There are no rollup standards. Just recommendation. Different import styled does not make your code (it's config) worse. And yes. It's open source. And I spread MY point in MY projects.

I locked that conversation because the guy started to write threats. It was not healthy conversation.

**Comment by TrySound** [comment]
Added note to readme
https://github.com/TrySound/rollup-plugin-terser/blob/master/README.md#why-named-export

**Comment by green-pickle** [comment]
@TrySound I haven't seen a more mentally ill maintainer in a very long time. So you even wrote fuck you to rollup community in readme. Fuck you from rollup community too.

Really hope I'll be so lucky to never ever have to use any of your packages.

**Comment by TrySound** [comment]
If you think that having own point of view is illness I'm sorry. And thank you for your words. Being unpaid maintainer and having such nice feedback is a great opportunity.

**Comment by green-pickle** [comment]
@TrySound this is the path only you chose.

Instead of me, my colleagues, devs from the other issue saying a warm thank you, upvoting and recommending your package, you chose to force us create issues, dislike our configs, duplicate packages in npm for no reason, split community, dislike you as a person and waste our time thinking how to solve this in a least horrible way.

Good job, man, well done.  👏
