### ISSUE TITLE
Plugin breaks named functions declared as variable

### ISSUE THREAD

**Issue by HackbrettXXX** [TrySound/rollup-plugin-terser#35]
Input:
```
import xy from 'foo'

var a = function a() {
  a()
}

xy()
export { a }
```

Output:
```
import o from"foo";var r=function o(){o()};o();export{r as a};
```

Expected output:
```
import o from"foo";var r=function r(){r()};o();export{r as a};
```
The name of the function and the recursive call are renamed incorrectly. Note that this error only occurs when there are imports and exports.

The rollup.config I use:
```
import {terser} from "rollup-plugin-terser"

export default [
  {
    input: 'test.js',
    output: {
      file: "test-out.js",
      format: 'esm'
    },
    external: ["foo"],
    plugins: [terser()],
    treeshake: false
  }
];
```

I'm not entirely sure if this is a bug of this plugin, rollup or terser. The outputs of of rollup without this plugin or terser without rollup are correct, though.

**Comment by TrySound** [comment]
Try to pass this option
```
{
  compress: {
    // this option is buggy https://github.com/terser-js/terser/issues/333
    collapse_vars: false,
  }
}
```

**Comment by HackbrettXXX** [comment]
Thanks for the fast answer. Setting this property doesn't make a difference, though.

**Comment by TrySound** [comment]
Try to disable some options and open bug in terser repo. This plugin is a thin wrapper.

**Comment by HackbrettXXX** [comment]
https://github.com/terser-js/terser/issues/361
