### ISSUE TITLE
Can this be used with the Rollup API

### ISSUE THREAD

**Issue by matthew-dean** [TrySound/rollup-plugin-terser#39]
Can you give guidance on how to write both the un-minified and minified bundles without processing twice using `rollup.rollup` and `rollup.write`? The Rollup documentation doesn't cover this well, and the default export as written up in this documentation doesn't work with `rollup.write`.

**Comment by TrySound** [comment]
I think this answers your question very well. How to rewrite it to describe clearer?
https://github.com/TrySound/rollup-plugin-terser#includeexclude

**Comment by matthew-dean** [comment]
@TrySound How do you write files using that configuration using the Rollup JavaScript API? If you do `bundle.write` it asks for an output options object.

**Comment by TrySound** [comment]
Do you mean this?
```js
Promise.all([
  bundle.write({ file: 'lib.js', ... }),
  bundle.write({ file: 'lib.min.js', ... })
])
```

**Comment by matthew-dean** [comment]
@TrySound Wait, that works? It just picks one from the bundle that matches the name?

**Comment by matthew-dean** [comment]
Okay, I got this working with the above `bundle.write`, _BUT_ if I add a `banner` option to the output, it stops working. I've confirmed that the terser plugin seems to be the plugin that breaks inserting a banner, but I can't tell if this is a problem with this plugin or rollup.

**Comment by TrySound** [comment]
Terser is run after adding banner. To preserve comment follow this https://github.com/TrySound/rollup-plugin-terser#comments

**Comment by matthew-dean** [comment]
@TrySound Thanks for your quick feedback! I appreciate it!
