### ISSUE TITLE
Output options broken in 2.x (worked in 1.x)

### ISSUE THREAD

**Issue by jhildenbiddle** [TrySound/rollup-plugin-terser#4]
Output options that were working fine in 1.x are no longer working in 2.x. For example:

```javascript
output: {
  beautify: true,
  comments: /^!/
}
```

These options work fine with [terser](https://github.com/fabiosantoscode/terser) 3.8.2 directly, so all signs point to an issue with this plugin (introduced in 2.x).

Terser Test (RunKit): https://runkit.com/jhildenbiddle/5a5f810b72915300136013b2

**Comment by 42tg** [comment]
I have issues with the 2.x versions as well, 1.0.1 works out of the box but same configuration doesnt work with 2.0.2.

**Comment by Makio64** [comment]
same issue..

**Comment by TrySound** [comment]
Fixed in https://github.com/TrySound/rollup-plugin-terser/releases/tag/v3.0.0
