### ISSUE TITLE
Same constants name in multiple files: error in browser: Uncaught SyntaxError: Identifier 'o' has already been declared

### ISSUE THREAD

**Issue by frederikhors** [TrySound/rollup-plugin-terser#40]
I have a problem.

### EXPLANATION

In a website I navigate on page /one, the code in the _one.js_ file executes fine.

After a while I insert in the page (pjax, ajax: no matter how) the second code in _two.js_ file.

The browser complains with this error:

```error
Uncaught SyntaxError: Identifier 'o' has already been declared
- at two.js:1
```

### REPRODUCTION and SOURCE CODE

1. _rollup.config.js_:

    ```js
    import resolve from 'rollup-plugin-node-resolve'
    import commonjs from 'rollup-plugin-commonjs'
    import { terser } from 'rollup-plugin-terser'
    import multiInput from 'rollup-plugin-multi-input'

    export default {
      input: ['src/**/*.js'],
      output: {
        format: 'esm',
        dir: 'dist/js'
      },
      plugins: [
        multiInput({ relative: 'src' }),
        resolve({ browser: true }),
        commonjs(),
        terser()
      ]
    }
    ```

1. _src/one.js_:

    ```js
    const names1 = ['john1', 'carl1', 'bob1']
    names1.forEach(name1 => {
      console.log('name1:', name1, ', in names1:', ...names1)
    })
    ```

1. _src/two.js_:

    ```js
    const names2 = ['john2', 'carl2', 'bob2']
    names2.forEach(name2 => {
      console.log('name2:', name2, ', in names2:', ...names2)
    })
    ```

1. _dist/js/one.js_:

    ```js
    const o=["john1","carl1","bob1"];o.forEach(n=>{console.log("name1:",n,", in names1:",...o)});
    ```

1. _dist/js/two.js_:

    ```js
    const o=["john2","carl2","bob2"];o.forEach(n=>{console.log("name2:",n,", in names2:",...o)});
    ```

### QUESTIONS

How to fix this problem?

Can we "prefix" constants name based on file name?

If of course I put everything in just _one.js_ file it works but it's not possible because of the structure of the project.

**Comment by TrySound** [comment]
Can you reproduce this with only terser?

**Comment by willfarrell** [comment]
I just ran into the same issue when upgrading from `5.1.3` to `5.2.0` (but was `t`). Setting `toplevel: false` fixed it for me. It would be nice if there was a way to allow this use case separate files.

Idea: 
- have `toplevel` take a seed number so that the array index could be passed in (below example). ie `toplevel: 2`
- As @frederikhors mentioned, maybe allow it to take a string to prefix the var. ie `toplevel: '_'`

```
import { terser } from 'rollup-plugin-terser'

export default [{
    input: 'src/js/aria.js',
    output: 'public/js/bundle-ui.min.js',
}, {
    input: 'src/js/lite-youtube.js',
    output: 'public/js/lite-youtube.min.js',
}].map(bundle => ({
    input: bundle.input,
    output: {
        file: bundle.output,
        format: 'cjs',
        sourcemap: true
    },
    plugins: [
        terser({
            toplevel: false // <-- Adding this fixed it for me
        })
    ]
}))
```

**Comment by TrySound** [comment]
> After a while I insert in the page (pjax, ajax: no matter how)

It does actually matter because you chose es modules format. It should be loaded via `import()` function in browser. If you want to use manual script loading change format to iife, this will prevent collisions by isolating each modules scope.

**Comment by TrySound** [comment]
Just use the right formats for environments.
