### ISSUE TITLE
 (plugin terser) SyntaxError: Unterminated string constant

### ISSUE THREAD

**Issue by LiuduZero** [TrySound/rollup-plugin-terser#46]
The problem suddenly appeared, copied from another project and packaged

```
rollup-plugin-terser
rollup-plugin-filesize
```
```
 (plugin terser) SyntaxError: Unterminated string constant
(plugin filesize) TypeError: Cannot read property 'length' of undefined
```
![TIM截图20191107093650](https://user-images.githubusercontent.com/24452177/68355197-8000d500-0149-11ea-8ad4-ad2b1db02cba.png)
![TIM截图20191107103001](https://user-images.githubusercontent.com/24452177/68355223-97d85900-0149-11ea-80c8-f948c90c3a78.png)

**Comment by TrySound** [comment]
Hard to say anything without reproduction

**Comment by LiuduZero** [comment]
> Hard to say anything without reproduction

I don't know what happened, but after 3 days, I turn on the computer and run the package again, and it's all right
