### ISSUE TITLE
terser 4.4.1 regression carried by this plugin too

### ISSUE THREAD

**Issue by WebReflection** [TrySound/rollup-plugin-terser#49]
There is currently a [breaking regression in terser 4.4.1](https://github.com/terser/terser/issues/527) and I've got bitten via this lovely rollup plugin, 'cause it uses `"^4.1.0"` so whatever is latest `4` gets installed in a fresh new `npm i`.

As my code broke due this change, many others could have similar issues, so since the regression is reproducible and described in the ticket, I wonder if you could update *as a patch* this plugin with a fixed `"terser": "4.4.0"` version instead, so that things should *not* break in the wild.

Thank you in advance for considering this 👋

**Comment by WebReflection** [comment]
closing, as terser `4.4.2` fixed the issue already 👍

**Comment by TrySound** [comment]
Cool, thanks!
