### ISSUE TITLE
Using with "require"

### ISSUE THREAD

**Issue by rbiggs** [TrySound/rollup-plugin-terser#50]
I'm trying to use this with rollup plugin for gulp. However, gulp imports everything like this:

```javascript
const terser = require('rollup-plugin-terser')
```
This throws and error saying that gulp can't find anything in the plugin. I'm supposing the code is not compatible with commonjs require statements.

Using an es6 `import` won't work. Any suggestions?

**Comment by TrySound** [comment]
Same as for es modules. There is no magic here as with default exports.
```
import { terser } from 'rollup-plugin-terser'
const { terser } = require('rollup-plugin-terser')
```
