### ISSUE TITLE
Update serialize-javascript to 2.1.1 or later to pass npm-auditor-ci

### ISSUE THREAD

**Issue by vrockai** [TrySound/rollup-plugin-terser#57]
Npm auditor finds this issue:
```
npm-auditor-ci found 1 advisories.
name                  action                version  severity  title                 url                              
--------------------  --------------------  -------  --------  --------------------  ---------------------------------
serialize-javascript  rollup-plugin-terser  1.9.1    moderate  Cross-Site Scripting  https://npmjs.com/advisories/1426
```

Info from https://npmjs.com/advisories/1426:
### Overview
> Versions of serialize-javascript prior to 2.1.1 are vulnerable to Cross-Site Scripting (XSS). The package fails to sanitize serialized regular expressions. This vulnerability does not affect Node.js applications.
### Remediation
> Upgrade to version 2.1.1 or later.

**Comment by vrockai** [comment]
Oh, I see it's already dealt with in the master branch.

**Comment by nomaed** [comment]
@vrockai  When do you think an update version will be published to npm? There are some packages that have rollup-plugin-terser as their dependency.

**Comment by TrySound** [comment]
@nomaed 4 days ago
![image](https://user-images.githubusercontent.com/5635476/70859815-45e5d880-1f2a-11ea-8710-686e1d237094.png)

**Comment by nomaed** [comment]
Well duh! Of course I should have looked in NPM and not under Releases @  https://github.com/TrySound/rollup-plugin-terser/releases

Thank you :)
