### ISSUE TITLE
Don't override user option

### ISSUE THREAD

**Issue by eight04** [TrySound/rollup-plugin-terser#58]
https://github.com/TrySound/rollup-plugin-terser/blob/9243334fc160ffb4bb9c7bab37449ad61ba42c25/index.js#L33

It forces us to run [iife](https://www.npmjs.com/package/rollup-plugin-iife) plugin after terser hence the IIFE wrapper is not minified.

**Comment by TrySound** [comment]
to be honest its not clear to me what you trying to solve. module: true is totally valid for esm output.

**Comment by eight04** [comment]
By using the iife plugin, output format will be converted into IIFE while `outputOptions.format` is still `esm`.

Anyway, I think the plugin shouldn't override user settings. It is better to provide default settings that can be overridden by the user.

**Comment by TrySound** [comment]
I dont quite understand module: false would solve your problem without iife. Polluting global namespace is not good solution.

**Comment by eight04** [comment]
> I dont quite understand how module: false would solve your problem without iife. Polluting global namespace is not good solution.

With `module: true`, terser will mangle/strip top-level variables. Here is an example:
https://repl.it/@eight041/rollup-plugin-terser-48?language=nodejs

**Comment by TrySound** [comment]
I know how module flag work. I do not understand what is the problem you are solving. Could you describe it?

**Comment by eight04** [comment]
As I described above, when using rollup-plugin-terser within rollup-plugin-iife, we have to put the iife plugin *after* the terser plugin or the iife wrapper will be stripped.

To make it work, I have to turn off the `module` flag, but the current design prevents users from changing the `module` flag.

**Comment by eight04** [comment]
If you need a live example:
https://github.com/eight04/image-picka/blob/6a4805fc85d2433ceee35c82e58800300b6b1874/rollup.config.js#L55-L58

Currently, that branch uses https://github.com/TrySound/rollup-plugin-terser/pull/59 for building.

**Comment by TrySound** [comment]
got it. thanks. at first i thought you want to get rid from iife plugin.

i will accept pr 7-8 jan. now im away from computer. ping me if i will forget.

**Comment by shrinktofit** [comment]
https://github.com/rollup/rollup/issues/3315 Similar issue. But I think `module` should not be dropped. It does means that the input is ESM. I'll try to use `toplevel` option.

**Comment by TrySound** [comment]
Published 5.2.0
