### ISSUE TITLE
Cannot create a minified bundle

### ISSUE THREAD

**Issue by vimtaai** [TrySound/rollup-plugin-terser#6]
I was trying to move from using the `terser` package directly on my rollup bundles to using this plugin. I remember that in the past it used to work for me but now it does not work if I want to use the plugin.

My `rollup.config.js` is:

```javascript
import { terser } from 'rollup-plugin-terser'

const output = {
  format: 'iife',
  dir: 'build',
  sourcemap: true
}

if (process.env.BUILD === 'production') {
  output.file = 'bundle.min.js'
} else {
  output.file = 'bundle.js'
}

const plugins = []

if (process.env.BUILD === 'production') {
  plugins.push(terser())
}

const watch = {
  include: 'src/**'
}

export default {
  input: 'src/index.js',
  output,
  plugins,
  watch
}

```

I get the following output when I run the `rollup --config --environment BUILD:production`:

```
> rollup --config --environment BUILD:production

src/index.js → bundle.min.js...
[!] (terser plugin) TypeError: Cannot read property 'transform' of undefined
TypeError: Cannot read property 'transform' of undefined
    at Object.renderChunk[...]
```

Any ideas?

**Comment by TrySound** [comment]
@vimtaai Did you get warning about rollup peer dependency when you installed the new version of this plugin?

**Comment by vimtaai** [comment]
@TrySound yeah, I got one now that you mention it. Updating to `rollup@0.66.0` solved my problem. Thank you!

PS. Maybe you could include this version dependency in the README. It would help a lot of folks IMO.

**Comment by TrySound** [comment]
Done
