### ISSUE TITLE
Serialization now prevents use of nameCache option

### ISSUE THREAD

**Issue by developit** [TrySound/rollup-plugin-terser#61]
Hi there!  Terser's `nameCache` option allows specifying an object to use for consistently mangling names. One useful detail of this API is that the object is mutated in-place, which means it's possible to store the object after Terser runs and preserve names across compilations.

We have been [using this in microbundle](https://github.com/developit/microbundle/blob/c03b535cd61f21cb25275ae315252fea69d1cb96/src/index.js#L622) to populate newly mangled property names in a `mangle.json` file after compilation so that developers notice them when committing and have a chance to correct the generated names.

Now that rollup-plugin-terser offloads Terser to a worker via jest-worker, the `nameCache` object gets serialized and passed back to the worker, which means it no longer gets updated in-place.

**Comment by developit** [comment]
Ooh, it looks like there's already an open PR (#47) that implements this!

**Comment by TrySound** [comment]
Hi @developit I'm happy to add this feature. Do you mind to send another PR including test? The author of that PR is probably stuck.

**Comment by developit** [comment]
Will do!

**Comment by developit** [comment]
Alright, PR's up! Sorry for the delay there.
https://github.com/TrySound/rollup-plugin-terser/pull/62

**Comment by TrySound** [comment]
Published 5.2.0
