### ISSUE TITLE
Issue with regex

### ISSUE THREAD

**Issue by thednp** [TrySound/rollup-plugin-terser#65]
Have this string

```js
var spaces = "\x09\x0a\x0b\x0c\x0d\x20\xa0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029";
```

terser plugins makes it exactly

```js
var e="\t\n\v\f\r   ᠎             　\u2028\u2029"
```

**Comment by TrySound** [comment]
You can check here https://try.terser.org/ such output is produced by terser package. This plugin is just a thing wrapper around terser.

Could you rise an issue here https://github.com/terser/terser?

**Comment by thednp** [comment]
Sure thing, sorry I forgot.
