### ISSUE TITLE
Save a byte, remove line break at the end of minified files

### ISSUE THREAD

**Issue by fasttime** [TrySound/rollup-plugin-terser#66]
I'm currently using the Rollup API to generate files that I later minify with terser, so I decided to try rollup-plugin-terser and see if I could do the whole job in one go. 

While testing my new setup I couldn't help noticing that the files created with rollup-plugin-terser are invariably one byte longer than the output produced by terser directly, and the reason is a superfluous newline character at the end of the minified files.

I suspect this is not something strictly related to this plugin and actually has to do with the way Rollup writes files with `bundle.write`, just wanted to post the issue here in case something can be done.

If it helps, my (simplified) code looks something like this.

```js
const { rollup } = require('rollup');
const { terser } = require('rollup-plugin-terser');

async function minify(input, file, format)
{
    const bundle = await rollup({ input });
    await bundle.write({ file, format, plugins: [terser()] });
}
```

**Comment by TrySound** [comment]
Try to add this
https://rollupjs.org/guide/en/#outputcompact

**Comment by fasttime** [comment]
That's what I was missing, thanks!

Have you considered making this the default, or adding a warning when the option is not set?

I'm very new to this, but I could surely help with a PR if you prefer.

**Comment by TrySound** [comment]
This is not really this plugin responsibility. Also it's probably only one byte loss in any case.
