### ISSUE TITLE
`comments` handler is not working (and tests do not properly check)

### ISSUE THREAD

**Issue by brettz9** [TrySound/rollup-plugin-terser#68]
Hi,

Thanks for this very necessary plugin. Having some problems now though with the `comments` handler.

`comments` appears to have no effect; comments get added regardless of whether I return `false` or `true`.

And no matter whether I return `false` or `true` or throw within `comments` in your test file, your tests for the `comments` handler always pass. Note too that the targeted fixture, `test/fixtures/unminified.js`, has no comments, so the test for this is not going to catch any problems.

**Comment by TrySound** [comment]
I added test which works as expected. At least in the latest (v6) version. Please check.

**Comment by brettz9** [comment]
Yes, thank you, I see it seems to be working there now.
