### ISSUE TITLE
(plugin terser) SyntaxError: Unexpected token: operator (<)

### ISSUE THREAD

**Issue by deligent-ant** [TrySound/rollup-plugin-terser#69]
rollup ts project

(plugin terser) SyntaxError: Unexpected token: operator (<)

resoleved

**Comment by deligent-ant** [comment]
`typescript({
        lib: ['es5', 'es6', 'dom'],
        target: 'es5',
        jsx: 'react',   // this config resolved solved my question
        allowSyntheticDefaultImports: true,
        exclude: 'node_modules/**'
      }),`

**Comment by TrySound** [comment]
Ok
