### ISSUE TITLE
Add top-level await support

### ISSUE THREAD

**Issue by rnstlange** [TrySound/rollup-plugin-terser#73]
```ts
const f = async (): Promise<void> => {
	console.log('TEST')
}

await f()

export {}

```

With my rollup config it compiles into:

```js
const f = async () => {
    console.log('TEST');
};
await f();
```

But using rollup-plugin-terser i getting:

`[!] (plugin terser) SyntaxError: Unexpected await identifier inside strict mode
SyntaxError: Unexpected await identifier inside strict mode`

My rollup config:

```js
import resolve from '@rollup/plugin-node-resolve'
import typescript from 'rollup-plugin-typescript2'
import { terser } from 'rollup-plugin-terser'
import run from '@rollup/plugin-run'

import buildins from 'builtin-modules'
import { dependencies } from './package.json'

const production = !process.env.ROLLUP_WATCH

export default {
	input: './src/index.ts',
	output: {
		file: 'app.js',
		format: 'esm',
	},

	external: [...buildins, ...Object.keys(dependencies)],

	plugins: [
		production && resolve({ preferBuiltins: true }),
		typescript(),
		production && terser(),
		!production && run({ execArgv: ['--harmony-top-level-await'] }),
	],
}

```

terser version: 4.6.10
rollup-plugin-terser version: 5.3.0

Sorry for my bad english

**Comment by TrySound** [comment]
This is related to [terser](https://github.com/terser/terser) package. This plugin is a thing wrapper around terser.

**Comment by lamualfa** [comment]
@TrySound A few days ago the `terser` package just added support for these needs. But unfortunately they haven't released the latest version for the latest commit.

See https://github.com/terser/terser/commit/69e250b6754b84afc6b86b177052730cff847461

**Comment by TrySound** [comment]
Ok. Still not related to this plugin.
