### ISSUE TITLE
Offer rollup-plugin-terser as ES6 module

### ISSUE THREAD

**Issue by dilyanpalauzov** [TrySound/rollup-plugin-terser#76]
I want to create an "index.html" file with rollup, which contains a `script type=module` and `script nomodule` tags.  Per https://github.com/rollup/rollup/issues/3536 rollup cannot call rollup/plugin-html once the ES6 and ES5 outputs are ready. So I am trying to switch to `rollup API` : `rollup.rollup().write()`.  In package.json I have `"type":"module"` and in the file with `rollup.rollup(…).write(…)` I insert `import {terser} from 'rollup-plugin-terser' as I had it in the `rollup.config.js` file.

Node 14 says `rollup-plugin-terser is expected to be in CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default exports`.

* Add `module` to package.json and allow the plugin to be loaded as ES6 module.

**Comment by TrySound** [comment]
Please check v6.1.0
