### ISSUE TITLE
Optional chaining support

### ISSUE THREAD

**Issue by EricRovell** [TrySound/rollup-plugin-terser#81]
I am using this plugin with svelte template.

During the development everything works fine. During the build process I got an error:

```(plugin terser) SyntaxError: Unexpected token: punc (.)```.

More specifically:

```
src/main.js → public/build/bundle.js...
  1932 |       // or from named props
  1933 |       // check if shorthand -> make full, ex: "123" -> "112233"
> 1934 |       if (Array.isArray(values) && values?.length) {
       |                                          ^ Unexpected token: punc (.)
  1935 |         [ red, green, blue ] = values
  1936 |           .map(value => value.length === 2 ? value : value + value);
  1937 |       }
```
I hope optional chaining support will be included in future versions, thank you!

**Comment by TrySound** [comment]
Not related to this plugin. Rollup supports optional chaining. Address this in terser repo https://github.com/terser/terser

**Comment by EricRovell** [comment]
Got it, thank you!
