### ISSUE TITLE
Support for optional chaining

### ISSUE THREAD

**Issue by felixapitzsch** [TrySound/rollup-plugin-terser#89]
Please upgrade to the latest version of terser (>= 5.2.0) in order to support optional chaining.
See https://github.com/terser/terser/issues/643

**Comment by TrySound** [comment]
Duplicate of https://github.com/TrySound/rollup-plugin-terser/issues/85

**Comment by felixapitzsch** [comment]
Sorry for the potentially duplicate issue. I only checked open issues and open pull request before submitting and the master branch is still at terser 5.0.0. 

I am a little bit confused now: it looks like there already was a pull request adressing this issue, but it was closed without being merged? If so, we can close this issue as duplicate and reopen #85. Btw, upstream terser already is at 5.3.0 now.

Anyways, it would be great to have a new release of rollup-plugin-terser on npm that actually reflects the bump to terser 5.2.0, 5.2.1 or 5.3.0.

**Comment by TrySound** [comment]
The project does not stick with specific terser version. Whole `5.*.*` range is allowed. It's a waste of time to release new version for every transitive change. Only major releases requires this. To upgrade your terser version you can remove it from your lockfile and run install again.

**Comment by felixapitzsch** [comment]
You are right. `"terser": "^5.0.0"` should include terser 5.3.0. This pull request does not make alot of sense it general. It only solved my problem, because I slightly missed my npm update depth before. A sufficient `--depth` option for `npm update` should have resolved my problem, too.

(Off-topic) Regarding the problems with open-wc I mentioned in https://github.com/TrySound/rollup-plugin-terser/pull/84#issuecomment-687251856 , the real problem is that multiple different versions of rollup-plugin-terser are being pulled in by open-wc, including `"rollup-plugin-terser": "^5.2.0"` and `"rollup-plugin-terser": "^6.1.0"`, which will not use a sufficiently new version of terser. But this cannot be solved here.
