### ISSUE TITLE
Update serialize-javascript on rollup-plugin-terser version 5.x

### ISSUE THREAD

**Issue by raphaelbs** [TrySound/rollup-plugin-terser#90]
I'm trying to fix [vulnerability issues regarding `serialize-javascript` below version 3.1](https://portswigger.net/daily-swig/remote-code-execution-vulnerability-exposed-in-popular-javascript-serialization-package).

I'm using Workbox v5 which is dependant on rollup-plugin-terser v5. Workbox v5 can't update to v5+ because [they need to keep the node support](https://github.com/GoogleChrome/workbox/issues/2601#issuecomment-674084452).

Is viable to update `serialize-javascript` on version 5 alone and release it as v5.3.1?

**Comment by TrySound** [comment]
Published 5.3.1 with upgraded serialize-javascript.

**Comment by dasa** [comment]
5.3.1 is now tagged as latest: https://www.npmjs.com/package/rollup-plugin-terser

**Comment by TrySound** [comment]
Good catch. Thanks. Released 7.0.2

**Comment by raphaelbs** [comment]
Much appreciated!
