### ISSUE TITLE
No change in 7.0.1 -> 7.0.2 ?

### ISSUE THREAD

**Issue by thisconnect** [TrySound/rollup-plugin-terser#92]
Why the 7.0.2 release https://github.com/TrySound/rollup-plugin-terser/compare/v7.0.1...v7.0.2 ?

**Comment by TrySound** [comment]
Latest tag fix
https://github.com/TrySound/rollup-plugin-terser/issues/90#issuecomment-687286258

**Comment by TrySound** [comment]
Added description
https://github.com/TrySound/rollup-plugin-terser/releases/tag/v7.0.2
