### ISSUE TITLE
unused function removed

### ISSUE THREAD

**Issue by logustra** [TrySound/rollup-plugin-terser#93]
## Bug report
Unused functions are removed when using these options
```
compress: false,
mangle: false
```

### Rollup
```js
// rollup.config.js
import { terser } from 'rollup-plugin-terser'

export default {
  input: 'main.js',
  output: {
    file: 'main.min.js',
    format: 'es'
  },
  plugins: [
    terser({
      compress: false,
      mangle: false,
    })
  ]
}
```

### Input
```js
// main.js
function hello() {
  console.log('hello')
}
```

### Output
```js
// main.min.js
```

### Expected
```js
// main.min.js
function hello(){console.log("hello")}
```

## Note
I've tried in terser website https://try.terser.org/ and working as expected
I've tried also with webpack and working as expected

**Comment by TrySound** [comment]
Hey, please check the output without terser plugin. This is not a bug. Rollup treeshakes the code.

**Comment by logustra** [comment]
@TrySound 
thanks for the information
solved by set `treeshake: false` in `rollup.config.js`

**Comment by TrySound** [comment]
What's the problem are you trying to solve?

**Comment by logustra** [comment]
just want to try to minimize code using rollup and terser without removing unused code as my current structure is very messy.
example: detected as unused code by rollup but in the real case I used that code 🤣

**Comment by TrySound** [comment]
How is it? Do you expect top level to be defined in window?

**Comment by logustra** [comment]
here's my previous structure (will refactor it bit by bit)
```javascript
// main.js
function hello() {
  console.log('hello')
}
```

```javascript
// home.js
// code inside this file will be injected to main.js if users go to home page
hello()
```

**Comment by TrySound** [comment]
Well, yes. If you expect legacy "type=script" behaviour this is the way. Though better to refactor with es modules eventually.
