### ISSUE TITLE
Typing error in plugin options

### ISSUE THREAD

**Issue by bennypowers** [TrySound/rollup-plugin-terser#94]
```js
// @ts-check
import { terser } from 'rollup-plugin-terser';

export default {
  input: 'file.js',
  output: { type: 'es', file: 'dist.js' },
  plugins: [terser({ output: { comments: false })],
}
```

> Argument of type '{ output: { comments: boolean; }; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'output' does not exist in type 'Options'.ts(2345)

**Comment by TrySound** [comment]
This project only reuse terser types. Please rise an issue in terser repo https://github.com/terser/terser

**Comment by dilyanpalauzov** [comment]
I opened https://github.com/terser/terser/issues/835.

**Comment by dilyanpalauzov** [comment]
My reading of https://github.com/terser/terser/issues/835#issuecomment-699535304 is that the correct call is
```javascript
terser({format: {comments: /^RRR/}})
```
while
```javascript
terser({output: {comments: /^RRR/}})
```
is wrong, as far as TypeScript forms are concerned.

Please substitute in https://github.com/TrySound/rollup-plugin-terser/#comments `output` → `format`.

**Comment by bennypowers** [comment]
Confirmed that worked in my app. Thank you!
