### ISSUE TITLE
Nullish coalescing / optional chaining support

### ISSUE THREAD

**Issue by VovanNet** [TrySound/rollup-plugin-terser#98]
Are there any plans to upgrade to terser 5.2.0+ with Nullish coalescing / optional chaining support in the near future? (https://github.com/terser/terser/issues/567)

**Comment by TrySound** [comment]
Terser is restricted to any `5.*` version here. You can reinstall this plugin to get the latest terser version.
https://github.com/TrySound/rollup-plugin-terser/blob/master/package.json#L38
